### ISSUE TITLE
String error with XML doctype

### ISSUE THREAD

**Issue by Soviut** [kylekatarnls/jade-php#10]
I was planning on writing my sitemap.xml in jade but the following
```jade
doctype xml
```
Throws
```
PHP Parse error:  syntax error, unexpected 'version' (T_STRING) in jade.stream://data;<?xml version="1.0" encoding="utf-8" ?>\n\n on line 1
```
Additionally, if I try to use escaped HTML I get the same error
```jade
| <?xml version="1.0" encoding="utf-8" ?>
```
I tried removing the `version` attribute and it then threw an error about the `encoding` attribute.

**Comment by Soviut** [comment]
The issue was that my development VM had [short_open_tag](http://php.net/manual/en/ini.core.php#ini.short-open-tag) enabled in php.ini. This was causing `<?` at the beginning of the XML doctype to be interpreted as code.

**Comment by kylekatarnls** [comment]
OK, thanks for the info.
