### ISSUE TITLE
Issues with attributes inside mixins

### ISSUE THREAD

**Issue by B7th** [kylekatarnls/jade-php#12]
Hi, thank you for this template. I noticed some issues with mixins and attributes:
```
mixin text(name,value="")
  input(id=attributes.id type="text" name!=name value!=value)&attributes(attributes)
+text('Lo','Li')#Lu(data-le="La")
Result:
<input id=''Lu'' type='text' name='Lo' value='Li'/>
```
There are two single quotes around specifically-added attributes (a test of `print $attributes['id'];` in the mixin shows `'Lu'`), and &attributes has no effect.

Thank you for looking into it!

**Comment by kylekatarnls** [comment]
Hi, ```&attributes(attributes)``` is now supported. Upgrade and enjoy!
