### ISSUE TITLE
Arrays in iterrations in attributes

### ISSUE THREAD

**Issue by proorlov** [kylekatarnls/jade-php#15]
it failed:
each item in items
a(href="#{item.url}") #{item.name}

but it works:
each item in items
a(href="") #{item.url} #{item.name}

have you an idea?

**Comment by brenwell** [comment]
Hey there, I am having a similiar issue. Thanks for any help in advance.

```jade
        each game in games
                h4 #{game.theme}
                img(src="/assets/img/games/#{game.theme}.jpg")
```

creates

```html
<p>fruit-theme</p>
<img src="<br />
<b>Notice</b>:  Array to string conversion in <b>jade.stream://data;<!DOCTYPE html><html lang=" en' class="no-js">
```

from

```php

["games"]=>
  array(11) {
    [0]=>
    array(3) {
      ["code"]=>
      string(20) "FRUIT"
      ["theme"]=>
      string(4) "fruit-theme"
      ["name"]=>
      string(12) "Fruity Fun"
    }
    [1]=>
    array(3) {
      ["code"]=>
      string(15) "CAR"
      ["theme"]=>
      string(3) "car-theme"
      ["name"]=>
      string(6) "Crazy Cars"
    }

```

Any ideas?

**Comment by proorlov** [comment]
yes..
but it works on ronan-gloo/jade-php
but ronan-gloo/jade-php has other problems
does anybody know file and string number for parsing it?

**Comment by strobox** [comment]
I use such syntax img(src="/assets/img/games/".$game->theme.".jpg") and it's works

**Comment by proorlov** [comment]
thnx

**Comment by kylekatarnls** [comment]
Yes, make the #{} works everywhere in PHP is very tricky, prefer PHP syntaxes. For an exactly equivalent rendering, use the native JS engine (https://github.com/superjimpupcake/PHPNativeJadeRenderer).
