### ISSUE TITLE
single or double quot option

### ISSUE THREAD

**Issue by proorlov** [kylekatarnls/jade-php#16]
https://github.com/proorlov/jade-php/commit/558e5597c8e446d523a93e1d8a5b80bef86110b3

**Comment by kylekatarnls** [comment]
Thanks. If you want your name in contributors, please make a pull request with it. But, make the $singleQuotes the last argument, else it will break the implementations that use $filters.

**Comment by kylekatarnls** [comment]
Thanks, implemented here: https://github.com/kylekatarnls/jade-php/pull/32
