### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by volter9** [kylekatarnls/jade-php#18]
Hello, there! Thank you very much for porting Jade to PHP, you've made huge amount of work and it's really appreciated, but there are some flaws that I've noticed when I was using Jade-PHP:

* Empty content exception. One of my templates has a conditional for displaying comments based 
  on `PHP_SAPI` and other factors. Basically, when my template outputted nothing Jade would throw an 
  exception. I had to output a comment instead. Maybe you shouldn't limit the empty output?
* Passed extension in options. This was confusing one. I was converting my old php templates into jade, 
  I didn't changed all templates extensions to `'.jade'` yet, but passed `'.php'` as ``extension`` in `Jade\Jade` 
  constructor and included one of my templates via Jade's `include` without the extension. For some 
  reason I've got the error that `blocks/head.jade` wasn't found. I found in sources that Jade appends
  `'.jade'` extension in case if file extension wasn't explicitly specified. That was confusing. Maybe you 
  should pass extension and options to `\Jade\Parser`?
* Only files can be cached. I don't remember exactly how does it happened, but I got the exception that 
  only files can be cached. I set `cache` key in `\Jade\Jade`'s constructor. Maybe you should fallback to 
  stream in case if passed `$input` isn't a file?
* README and examples. I think you need to put a link pointing to `tests/` directory into description with 
  caption 'Examples'. Those examples are extremely helpful to understand how does Jade-PHP works, 
  and probably some people miss them out, because falsely thinking that there are no examples 
  or documentation.

Everything, so far, works perfect! These are just some suggestions that I think may improve Jade-PHP :) 

Thanks for the hard work again! :bow: 

**UPD**: ToDo list:

- [X] Fix else if/elseif
- [X] Allow empty content
- [x] Pretty output
- [ ] Set output indentation level
- [ ] Conditional attributes
- [ ] `Only files can be cached` occasional exception
- [ ] Improve `README.md`

**Comment by volter9** [comment]
There's one more think I wanted to suggest:

* Pretty printing. The cached templates are pretty printed, but output isn't "prettified". I discovered some time ago a trick that allows prettily format PHP template output. All you need to do is for every `<?php ... ?>` code is to put one space character after closing PHP preprocessor tag. PHP closing tags "absorb" one newline character after `?>`, so the solution is simply insert one space after `?>` :)

**Comment by volter9** [comment]
Also, it seems like Jade-PHP has some incompatibilities with Jade in JS:

* `else if` isn't working. It's converted into `else(if $something)`. I changed regular expression in Lexer.php from `'/^(if|unless|else if|else)\b([^\n]*)/'` to `'/^(if|unless|elseif|else)\b([^\n]*)/'` on line 474, and it's working with `elseif $condition`.
* Conditional attributes doesn't seem to work.

P.S.: I don't push you to fix the issues. I just pointing out which suggestions I have and which problems I found. For now it's discussion. If in some of these points you're interested, I might send few pull requests to fix/add functionality. Jade is awesome :fire: :fire: :fire:

**Comment by kylekatarnls** [comment]
Do not hesitate to submit pull requests. I tried my best to fix some little bugs of the amazing @ronan-gloo work. Now, when I work with PHP, I prefer to install node.js and use the native jade package then call it throught a PHP wrapper or shell_exec. I recommand this approach if you can and to use jade-php only if you cannot install the native jade engine.

However, all contibutions are welcome.

**Comment by volter9** [comment]
> I prefer to install node.js and use the native jade package then call it throught a PHP wrapper or shell_exec

It's a good workaround, however, using PHP functions (which are already loaded by PHP or will be through autoloader) is incredibly handy feature. With wrapper, you can't execute PHP code within jade templates.

> However, all contibutions are welcome.

I will, but I fear that PR is going to be ignored or rejected (so I'll just waste my time on nothing). That's why I created this issue, to discuss which my suggestion are welcomed, and which aren't. :)

There's one more thing I noticed when I was working jade-php: the scope of variables. 

I shoot myself in the foot while naming or using same named variables in different views. Is the behavior is the same in node.js jade?

**Comment by volter9** [comment]
@kylekatarnls I tried to run the tests by `cd`ing to tests directory and running `php test.php`, but it's giving me the fatal error:

```
 rendering test 'attrs.interpolation'
! FATAL: php exception: exception 'Exception' with message 'Unexpected value:  . id . ''' in /Users/Volter/.../jade-php/src/Jade/Compiler.php:545
```

Is it supposed to be like that?

**Comment by kylekatarnls** [comment]
Hi, it should be fixed in my last commit. And we reach now 83% but there is a dilemma: Or we choose to PHPize the Jade syntax to allow PHP functions, classes etc. or we keep the JS syntax but we cannot permit easily to call PHP from it. IMHO, as you sayed, the strict JS syntax should be the native engine purpose, and in jade-php, we should change a little the Jade syntax to match PHP syntax (dollars, dot to concat strings, etc.) and so, we will can use PHP within in. But the JS jade templates will not be compatible with jade-php.

**Comment by volter9** [comment]
@kylekatarnls as for me, I think PHPization is the right choice, because:

1. Even without PHPization, node.js jade templates aren't going to work with jade-php, only variable definition and dot syntax. Other JS features as Array.prototype.* and String.prototype.* aren't going to work with jade-php
2. Jade-PHP is adaptation of node.js jade to PHP, so it doesn't mean that it should be compatible with node.js jade

For variable definition, I use native PHP variable definition instead of JS `var`, because it's more semantic (I use some of the functions inside of the jade templates, and it works great), but that's a matter of opinion.

> Hi, it should be fixed in my last commit

Great, thank you! :)
I'll slowly start studying the code, and creating some PR's.

**Comment by kylekatarnls** [comment]
Hi, there is a problem with the space after ?>, with PHP calculated attributes, you get ```foo="bar[space]"``` instead of ```foo="bar"```, so I must disable this feature until we find a way put this space only if the ?> is followed with a new line.

**Comment by kylekatarnls** [comment]
Some of the suggestions here are now implemented, I extracted some other to assign them to milestones. I close this one to clean a little the issues list, please feel free to open new ones about specific point you wish to see implemented.
