### ISSUE TITLE
How to pass variables to Filters

### ISSUE THREAD

**Issue by openmarco** [kylekatarnls/jade-php#19]
Hi!

We want to add new filters (for example, “striptag”) but it doesn’t work correctly.

We’ve added a new Striptag class as described [here](https://github.com/kylekatarnls/jade-php) in the '**Supports for custom filters**' section:

```php
use Jade\Nodes\Filter;
use Jade\Compiler;
use Jade\Filter;

class Striptag Extends AbstractFilter {
  public function __invoke(Filter $node, Compiler $compiler) {
    $output = array();
    foreach ($node->block->nodes as $line) {
      $output[] = $compiler->interpolate($line->value);
    }
    $output_string = implode("\n", $output);
    $out_strip = strip_tags($output_string);
    // Return string
    return $out_strip;
  }
}
```

Jade template:

```Jade
user = array('name' => '<strong>tobi</strong>', 'age' => 2)

:striptag
  #{user.name}
```

In the output we get an empty string since variable `$output_string` has a value like that:
```php
"<?php echo htmlspecialchars(\Jade\Compiler::getPropertyFromAnything($page, 'post_content')) ?>"
```
A `strip_tags(...)` function removes all tags in the string, and a template does not receive any data.

What needs to be done in order to receive a value of a variable instead of PHP code which outputs this value of a variable?

Thank you!

**Comment by kylekatarnls** [comment]
I think a strip_tags filter can be done like the escape filter : https://github.com/kylekatarnls/jade-php/blob/master/src/Jade/Filter/Escaped.php

```php
<?php
use Jade\Compiler;
use Jade\Nodes\Filter;
class Escaped extends AbstractFilter {
    public function __invoke(Filter $node, Compiler $compiler)
    {
        return strip_tags($this->getNodeString($node, $compiler));
    }
}
```

Please let me know if it do the trick.

**Comment by kylekatarnls** [comment]
I consider this is fixed but feel free to re-open if you have questions.
