### ISSUE TITLE
Undefined function array_get in Jade\array_get() in \kylekatarnls\jade-php\src\Jade\Parser.php on line 111

### ISSUE THREAD

**Issue by strobox** [kylekatarnls/jade-php#20]
I'm understand what this function should do, but where it's definition? It is some util function?

**Comment by zorca** [comment]
Looks like Laravel array_get() Helper Function: http://benjaminkohl.com/post/laravel-array-get-helper-function

**Comment by kylekatarnls** [comment]
Yes, it's a mistake in Parser.php, it's mean the Jade template has a syntax error. But I will fix it to get a clear error message.

**Comment by kylekatarnls** [comment]
Please update jade-php to the master, it should be give you a verbose error such as "expected something but got something else".
