### ISSUE TITLE
variables in attributes raise uncaught exception "Unexpected value"

### ISSUE THREAD

**Issue by dadaphl** [kylekatarnls/jade-php#27]
``` div #{templateurl} ``` works
``` div(class="#{templateurl}") ``` doesn't work
```
( ! ) Fatal error: Uncaught exception 'Exception' with message 'Unexpected value: . templateurl . ""' in /foo/bar//vendor/kylekatarnls/jade-php/src/Jade/Compiler.php on line 545
( ! ) Exception: Unexpected value: . templateurl . "" in /foo/bar/vendor/kylekatarnls/jade-php/src/Jade/Compiler.php on line 545
```

**Comment by volter9** [comment]
Try just `div(class=templateurl)`

**Comment by dadaphl** [comment]
thanks volter9, that works!
how would i do this?
```
img(src="#{templateurl}/image/test.png")
```

**Comment by dadaphl** [comment]
got it
```
img(src=templateurl . "/image/test.png")
```

**Comment by volter9** [comment]
I'm not really sure why this:

```jade
img(src="#{templateurl}/image/test.png")
```

Doesn't work for you, while working for [me](https://github.com/volter9/volter9/blob/master/theme/blocks/likely.jade). Which version of Jade-PHP do you use?

**Comment by kylekatarnls** [comment]
Now we reach the primary goal, maybe we can see for those kind of interpolations.

**Comment by kylekatarnls** [comment]
Hi, I consider this is fixed in the new version,if it's not, feel free to re-open this issue.
