### ISSUE TITLE
jade.stream not working on some PHP installations

### ISSUE THREAD

**Issue by dreerr** [kylekatarnls/jade-php#34]
The library is working fine on my local PHP installation, but as soon I transfer the data to my Webhost Hosteurope it only works in cached mode on the second refresh, thus only when the generated cachefile ist served. There is no error, or anything to debug. It seems the `jade.stream://data;…` isn't working/allowed. Also changing the `stream` option didn't work. Any idea on this?

**Comment by kylekatarnls** [comment]
First, can try to set the flag allow_url_include On in your php.ini file?

**Comment by dreerr** [comment]
Turned on, still not working.
Full phpinfo here: https://dl.dropboxusercontent.com/u/1352550/phpinfo.html

**Comment by kylekatarnls** [comment]
Have you an exception message? If you haven't, can you tell me what you expect and what you get? Is the bug present with any jade file (even if you try with a very basic template such as a single-line file with `p Hello`)?

Thanks for helping us improve the library.

**Comment by dreerr** [comment]
Also a single line is not working. No exceptions are listed. If cache is turned on, it only works on the second request (when the cache file is generated and served)

**Comment by dreerr** [comment]
must have to do with the jade.stream:// and the include $file of function render…

**Comment by kylekatarnls** [comment]
Sorry but I need to know what is "not working", what exactly appears on your browser? A blank page? The jade source code? An PHP error? An Apache error? And if it's an error I need the message.

**Comment by dreerr** [comment]
**UPDATE** After some digging I found out that **Suhosin** was responsible for the error. It worked after adding `jade.stream://` to `suhosin.executor.include.whitelist`

**Comment by kylekatarnls** [comment]
Thanks! Very happy to hear that. Maybe we should try to detect these error and throw an explicit message like "Suhosin block jade stream, please add jade.stream:// to suhosin.executor.include.whitelist". I will study it.

**Comment by kylekatarnls** [comment]
I think I will simply take the code Symfony use to check phar is whitelisted:
https://github.com/symfony/symfony/search?utf8=%E2%9C%93&q=suhosin.executor.include.whitelist

**Comment by dreerr** [comment]
😎🌟
