### ISSUE TITLE
suggestion setting for already escaped content

### ISSUE THREAD

**Issue by dreerr** [kylekatarnls/jade-php#43]
I'm using your class inside this [Template Language Module](https://github.com/dreerr/TemplateEngineJade) for [ProcessWire](https://processwire.com/). My problem is that the ProcessWire CMS already takes care of escaping my variables, so I have to write `!=` for every variable used. How about a setting for already escaped content or a possibility to customize `const ESCAPED` and `const UNESCAPED`?

**Comment by kylekatarnls** [comment]
First, I think, this should be handled in the ProcessWire or in your wrapper. See if you have the same problem with {{ var|escape }} and the Twig engine. I you have, the good solution would be to unescape your data in your wrapper or ask ProcessWire to give you a config setting. Else you can extends Compiler like this:
```php
namespace Jade;

class UnescapedCompiler extends Compiler {
    const ESCAPED = 'echo %s';
}

class UnescapedJade extends Jade {
    /**
     * @param $input
     *
     * @return string
     */
    public function compile($input)
    {
        $parser = new Parser($input, null, $this->options['extension']);
        $compiler = new UnescapedCompiler($this->options, $this->filters);
        return $compiler->compile($parser->parse($input));
    }
}
```

But I really not recommand to do that. It's not safe in my humble opinion.

**Comment by dreerr** [comment]
Thanks Kyle! I agree that this is a potentially unsafe solution. But by default any Text field in ProcessWire has a `htmlspecialchars` TextFormatter activated and any Textarea field should be unescaped. 

But it would be better to accustom the use of `!=` respectively `=`

I ended up making it an option in my wrapper 😇
