### ISSUE TITLE
Calculation problems in variable

### ISSUE THREAD

**Issue by herrbischoff** [kylekatarnls/jade-php#51]
I'm trying to calculate the dimensions of a `div` container based on those of an image (the values are given elsewhere). The following mixin should work. I have tested it interactively on the Jade website and it works as expected:

```jade
mixin image(img, width, height)
  - var ratio = height / width * 100
  div.image(style='background-image: url(' + img + '); padding-bottom: ' + ratio + '%')
```

But in jade-php this results in `ratio` getting a value of `INF` instead of the correct result.

This however outputs the correct value of `height`:
```jade
mixin image(img, width, height)
  - var ratio = height / width * 100
  div.image(style='background-image: url(' + img + '); padding-bottom: ' + height + '%')
```

This outputs the correct value of `width`:
```jade
mixin image(img, width, height)
  - var ratio = height / width * 100
  div.image(style='background-image: url(' + img + '); padding-bottom: ' + width + '%')
```

This calculates the correct value:
```jade
mixin image(img, width, height)
  - var ratio = 1911 / width * 100
  div.image(style='background-image: url(' + img + '); padding-bottom: ' + ratio + '%')
```

Is it something I'm doing wrong or is there something broken with jade-php. I appreciate any kind of feedback as I am using it in an active project. Thanks!

**Comment by kylekatarnls** [comment]
Hi, As we want use PHP syntaxes like NameSpace\ClassName::method() in interpolations, we cannot use JS "+" concatenation, we must use PHP dot:
```jade
div.image(style='background-image: url(' . $img . '); padding-bottom: ' . $ratio . '%')
```

If you want the scrit same syntaxe as JS-jade, use a native jade-js wrapper. But you will not be able to call PHP methods in your Jade template.

**Comment by herrbischoff** [comment]
Thanks for your reply but actually this does nothing for my case. The result of the **calculation** is still `INF`. Dots or pluses do not make a difference.

**Comment by kylekatarnls** [comment]
Inf means infinity, you probably divide by zero. Try:

```jade
mixin image(img, width, height)
  - var ratio = 1911 / $width * 100
  div.image(style='background-image: url(' . $img . '); padding-bottom: ' . $ratio . '%')
```

And first, call it with static values to be sure:
```jade
+image('foo', 20, 10)
```

**Comment by herrbischoff** [comment]
Thanks again. I'm not sure we're on the same page here. The issue is precisely that: whenever I give static values (like `1911`), it works. Whenever **both** values come from the mixin attributes `+image('foo', 20, 10)` and the calculation is `- var ratio = height / width * 100` it does not and `ratio = INF`.

**Comment by kylekatarnls** [comment]
ratio = INF means width = 0 in your case, I think you need $width, instead of width **and** you need to be sure $width != 0

**Comment by herrbischoff** [comment]
I'm sorry, but this still does not work. If I do what you propose, I get a 500 Internal Server Error.

There is definitely some kind of weirdness going on.

What I want to do is this (usage of the `$` in front of variables gives me a HTTP 500):
```jade
mixin image(img, width, height)
  - var ratio = $height / $width * 100
  div.image(style='background-image: url(' . $img . '); padding-bottom: ' . $ratio . '%')
```

I call the mixin like so, to test:
```jade
+image('foo', 1922, 1015)
```

However, this leads to the known `INF`. When I put even just one value directly into the mixin, it works. It doesn't even matter what variable I replace with an integer, either one is fine:
```jade
mixin image(img, width, height)
  - var ratio = height / 1922 * 100
  div.image(style='background-image: url(' + img + '); padding-bottom: ' + ratio + '%')
```

```jade
mixin image(img, width, height)
  - var ratio = 1015 / width * 100
  div.image(style='background-image: url(' + img + '); padding-bottom: ' + ratio + '%')
```

Both work.

Just this does not:
```jade
mixin image(img, width, height)
  - var ratio = height / width * 100
  div.image(style='background-image: url(' + img + '); padding-bottom: ' + ratio + '%')
```

What I forgot to mention is that I'm using it within ProcessWire via [this module](https://github.com/dreerr/TemplateEngineJade). It may be that there is some hiccup to be found there but I doubt it. I'd very much appreciate it if you could take a quick look. Thanks!

**Comment by kylekatarnls** [comment]
Sorry, I achieve your goal with:

```jade
mixin image(img, width, height)
  - $ratio = $height / $width * 100
  div.image(style='background-image: url(' . $img . '); padding-bottom: ' . $ratio . '%')
```

And + concat is also possible like this:

```jade
mixin image(img, width, height)
  - $ratio = $height / $width * 100
  div.image(style='background-image: url(' + img + '); padding-bottom: ' + ratio + '%')
```

But after a hyphen, you must have: a "var" declaration with no calculation, or a PHP expression.

I add this case to the unit tests.

Thanks

**Comment by herrbischoff** [comment]
Ahh, very nice. This approach works! Thank you very much for investigating the issue. This saves part of the project I'm working on right now. :) I'm closing it since it works now.
