### ISSUE TITLE
Cannot access static error

### ISSUE THREAD

**Issue by Soviut** [kylekatarnls/jade-php#6]
I migrated from https://github.com/ronan-gloo/jade-php to this fork but got the following error.
```
PHP Fatal error:  Cannot access static:: when no class scope is active in /vagrant/veteransfirst/vendor/kylekatarnls/jade-php/src/Jade/Compiler.php on line 615
```
I'm using PHP 5.3.3

**Comment by Soviut** [comment]
I'm not longer getting this error

**Comment by Soviut** [comment]
I've been able to get the issues again. The error is happening in Compiler.php on line 947:

```php
            array_walk($arguments, function (&$arg) {
                $arg = static::addDollarIfNeeded(trim($arg));
                if(strpos($arg, '=') === false) {
                    $arg .= ' = null';
                }
            });
```

This probably works in PHP 5.4 but in 5.3 you can't call a static function within a closure because the class scope isn't being passed into the closure. I'm using closures elsewhere  and I have to use the `use` keyword to pass variables into the closure's scope. Like the following:

```php
$router->post('/contact/partnersignup', function() use ($partnerSignupController) {
    $partnerSignupController->post();
});
```

**Comment by kylekatarnls** [comment]
Thanks, indeed, Jade-PHP is supposed to support PHP 5.3 and I broked it when I added this code. However Closure::bind require PHP 5.4 too. So the only way is probably to not use a static method but a dynamic one. I will check that.

**Comment by Soviut** [comment]
Just a heads up, I tried rewriting it as an instance method but I wasn't able to do `function() use ($this)` to pass the class scope into the closure. It gave an error (which I should have written down) specifically about not being able to pass `$this` to closures.

**Comment by kylekatarnls** [comment]
Yes, you cannot use ```$this``` this way, just do ```$context = $this;``` then pass ```$context``` in use().
