### ISSUE TITLE
Invalid + character used for string concat

### ISSUE THREAD

**Issue by Soviut** [kylekatarnls/jade-php#7]
The Compiler seems to be generating string concatenation code that uses `+` instead of `.`. This causes PHP to interpret strings as numbers and tries to add them. This results in `'' + 'whatever'` returning `0`.

Any time a Jade string has interpolated variables inside it, `\Jade\Compiler::strval()` is used and the strings are wrapped in blank strings like so `'' + $whatever + ''`. The `+` symbol means the strval is always `0`.

The following jade:
```jade
select.form__input.form__input--select(id='#{$form->name}_#{$field->name}')
```
is resulting in:
```php
<select id='<?php echo \Jade\Compiler::strval('' + $form->name + '_' + $field->name + '') ?>'>
```

**Comment by Soviut** [comment]
It turns out this happens here https://github.com/kylekatarnls/jade-php/blob/master/src/Jade/Lexer.php#L574

I'm going to do a PR to fix this

**Comment by kylekatarnls** [comment]
I confirm the bug, thanks for the report, I will wait for your PR.
