### ISSUE TITLE
Indented single-line comments interpreted as multi-line

### ISSUE THREAD

**Issue by ianmaddox** [kylekatarnls/jade-php#87]
Single line comments are interpreted as multi-line if they are indented two or more levels. The following sample template illustrates the problem:
```jade
doctype html
html.no-js
    //- <![endif]
    head
        title MySite
body
    h1 Hullo
    // One layer deep comment works fine
    h2 Subhead
    div.container
        // Two layer deep comment fail
        h3 Sub-Subhead
        h3 More nonsense
```

The official Jade (Pug) package renders as this:
```html
<!DOCTYPE html>
<html class="no-js">
  <head>
    <title>MySite</title>
  </head>
</html>
<body>
  <h1>Hullo</h1>
  <!-- One layer deep comment works fine-->
  <h2>Subhead</h2>
  <div class="container">
    <!-- Two layer deep comment fail-->
    <h3>Sub-Subhead</h3>
    <h3>More nonsense</h3>
  </div>
</body>
```

jade-php misinterprets a comment more than one layer indented as a multi-line comment and hides everything following it at that indentation level:
```html

<!DOCTYPE html>

<html class='no-js'>
  <head>
    <title>MySite</title>
  </head>
</html>
<body>
  <h1>Hullo</h1>
  <!-- One layer deep comment works fine-->
  <h2>Subhead</h2>
  <div class='container'>
    <!-- Two layer deep comment fail
        h3 Sub-Subhead
        h3 More nonsense
-->
  </div>
</body>
```

**Comment by anthonyhendrickson** [comment]
Weighing in! Looks as if this was introduced from in v1.7 (rc1 is unaffected). In addition to html single-line commenting, this also affects single-line jade comments >=v1.7

**Comment by kylekatarnls** [comment]
Thanks for the help. It's my next priority.

**Comment by kylekatarnls** [comment]
Hi @ianmaddox, your example is now rendered exactly as the official Pug do. Please update to 1.10.1 and tell me if anything goes as you wish.

Thanks to you and @anthonyhendrickson for the helping hand.
