### ISSUE TITLE
problem with `compile()` and local variable in mixin block

### ISSUE THREAD

**Issue by ayapi** [kylekatarnls/jade-php#88]
hello, i'm trying to use jade-php with `compile()` feature.

```php
$jade = new Jade([
  'prettyprint' => true,
  'extension' => '.jade'
]);
$jade->compile($jade_string);
```

```jade
mixin test
  div
    = $local_var
+test
```

`Undefined variable: local_var` raised.

```jade
mixin test
  block
+test
  = $local_var
```

also the same error.

i think, facades around mixins can't read variables on php after `compile()`.
how can i solve it?

**Comment by ayapi** [comment]
sorry, my reporting was wrong.
i'm trying to use this on Laravel.
and `$jade->render()` raises same error.
it seems my implementation is bad.

**Comment by kylekatarnls** [comment]
Hi, compile should not execute the template, you should probably use render with a jade string in the first argument and an array with your local vars in the second argument.

**Comment by ayapi** [comment]
@kylekatarnls 
thank you for ur reply!
i tried again on initial project (outside Laravel)

index.php
```php
<?php

require 'vendor/autoload.php';

use Jade\Jade;

$jade = new Jade();
$vars = ['test_var' => 'test_value'];
$content = $jade->render(file_get_contents('test.jade'), $vars);
echo $content;
```

test.jade
```jade
mixin test
  = test_var
+test
```

on terminal
```
composer init
composer require kylekatarnls/jade-php
composer install
php index.php
```

still get error `Undefined variable`.
the original javascript version jade renders `test_value`.
so I'd like jade-php to behave likewise. is it possible?
if i dont use mixin, jade-php renders correctly. but raises error in mixin.

**Comment by ayapi** [comment]
i read jade-php's source codes and compiled php code from my `test.jade`.
it generates `$GLOBALS['xxxx_mixin']`, and `recordMixinBlock()` etc, 
they have a closure function.
i dont know a lot about php, but i think those functions have different variable scope.
what do you think?

**Comment by kylekatarnls** [comment]
Yes, it's a big problem because, even if we add ```use (&test_var, &all_other_varnames)```, it will not work for vars declared in the template with ```- var a_new_var = 'foo'``` or if we use cache and dynamic varnames.

I'm sorry, the only option right now is:
```jade
mixin test(test_var)
  = test_var
+test(test_var)
```

**Comment by ayapi** [comment]
ah, definitely! you re very clever.
but how about "mixin block pattern" as follows?

```php
$jade = new Jade();
$vars = ['email => 'test@example.com'];
$jade->render('form.jade', $vars);
```

```jade
mixin form
  form(method="post", action="/")
    block
		
+form
  input(type="text", name="email", value=email)
```

this example raises `Undefined variable: email`.
i couldnt found a solution in this pattern.
maybe closure functions makes things complex...

**Comment by kylekatarnls** [comment]
I'm always wondering how to face this issue.

We have 3 scopes levels (outside mixin, inside, inside mixin block). JS allow child scopes (functions) to access parent scopes variables, PHP not.

Either we keep the PHP philosophy and try to adapt Pug to it (create a "use" keyword to specify manually wich variables to pass), or we must store all variables in an array and pass this array as a reference in use() of all scopes. But this means all generated and custom user codes should call the array instead of the variables.

**Comment by kylekatarnls** [comment]
Here is a possible work-around but it sounds to me like a war machine:

```jade
mixin a
  =b
  - b++
- b = 42
+a
=b
```

As we want get 42 43, the PHP should be something like:

```php

$a = function (&$varHandler) {
    foreach ($varHandler as $key => $val) { //*
        ${$key} = $val; //*
    } //*

    echo $b . "\n";
    $b++;

    foreach ($varHandler as $key => &$val) { //*
        $val = ${$key}; //*
    } //*
};

$b = 42;

$varHandler = get_defined_vars(); //*
$a($varHandler);
extract($varHandler); //*
unset($varHandler); //*

echo $b . "\n";

```

All lines with //* should be generated automatically to wrap every function call, and inside every function declararion to propagate variables values inside and variables changes outside.

Passing directly references seems not possible with what I tested ; global is too dangerous (will get variables that does not concern the view) and we cannot pass dynamically the variables names as the PHP code can be cached and so must be valid for different variables keys and values.

I will test that on a branch.

**Comment by kylekatarnls** [comment]
It's done and works well in the branch mixin-scope-propagate (#91) and it can be enabled/disabled with the setting restrictedScope:

```php
$pug = new Pug([ 'restrictedScope' => true ]);
// or
$pug->setOption('restrictedScope', true);
```

true is the current behavior on 1.10.4, false is the default behaviour in mixin-scope-propagate and it fixes the bug reported on the top of this topic and is the same as in pug-js.

But it add complexity in mixins make PHP cached template files bigger and slower if there are many variables. It can also use more memory if there are big variables.

So I wonder if new behaviour should be the default behaviour or if it should be set manually with the option.

**Comment by kylekatarnls** [comment]
restricedScope false will the default behaviour. If you do not use variables in mixins (except arguments), you can set it to true to optimize your cache size.
