### ISSUE TITLE
Unexpected value error

### ISSUE THREAD

**Issue by brenwell** [kylekatarnls/jade-php#9]
Hey there, thanks for the lib. I just updated composer and **jade-php** seems to be throwing these errors at me. Has something changed, eveything was working great before?

#### The error

```php
<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'Unexpected value:  . isMobile . &quot;&quot;' in /vendor/kylekatarnls/jade-php/src/Jade/Compiler.php:545
```

#### The data

```php
array(6) {
  ["role"]=>
  string(3) "all"
  ["isDev"]=>
  bool(true)
  ["isAdmin"]=>
  bool(true)
  ["isMobile"]=>
  string(5) "false"
  ["randomToken"]=>
  string(72) "38f658ba0ed03075b4dcc37127f19d40f0939a22e7afbbd1379ab78927ff660c6c84ecac"
  ["date"]=>
  string(4) "2015"
}
```

#### The template

```jade
extends base

block content
    .row
        .col-md-12
            .page-header
                h1 #{isMobile}
                br
```

Thanks in advance

**Comment by kylekatarnls** [comment]
Thanks for the report. Could you tell me if you updated to 1.3 or to some commit (maybe the last one of the master). If you don't know, please paste the jade-php line of your composer.

**Comment by brenwell** [comment]
Actually I am not sure sure how to tell. But I only updated yesterday so it must be whatever is currently available via composer. This is the entry I have in my `composer.json`.

```json

      "kylekatarnls/jade-php": "dev-master"

```

Anything else I can do to help?

**Comment by kylekatarnls** [comment]
I will inspect the PHP that your jade template generate. The most recent change is #8 and concern ```#{}``` syntax, it could be involved.

In production environnement, I recommand you to use only stable version for all your dependancies (not only jade-php). For example:
```"kylekatarnls/jade-php": "^1.3"```

**Comment by brenwell** [comment]
Oh oops my bad, will you use the release. Thanks for the help

```json
"kylekatarnls/jade-php": "^1.3"
```

**Comment by terion-name** [comment]
I've got the same error :(
```
li(class="#{(request()->route()->getName() == 'home' ? 'active' : '')}")
```
results in:
```
Exception in Compiler.php line 545:
Unexpected value: . (request()->route()->getName() == 'home' ? 'active' : '') . ""
```

**Comment by kylekatarnls** [comment]
Hi, I did many changes, can you upgrade and re-try please?

**Comment by kylekatarnls** [comment]
It is now covered with the test interpolation.jade and it does not throw error any longer. As we do not want to entirely rewrite a complete JS engine, the display will be handled by the native PHP string conversion, so false become "", true become "1" etc.
